#!/bin/bash

if [ -z "$1" ]; then
  echo "No link given"
  exit 1
fi

push_to_git() {
  # Make sure that we are up to date 
  cd $NICE_PATH
  git pull
  # Get the title of the link
  TITLE=$(get_title.py $1)
  echo "- [$TITLE]($1)" >> "$NICE_PATH/README.md"
  git add README.md #&> /dev/null 
  git commit -m "new link - $1" # &> /dev/null 
  git push #&> /dev/null & 
}

push_to_git $1
